structure(list(url = "https://cran.r-project.org/web/packages/hiiamnicandthisismypackage/DESCRIPTION", 
    status_code = 404L, headers = structure(list(date = "Fri, 31 May 2024 08:10:15 GMT", 
        server = "Apache", vary = "accept-language,accept-charset", 
        `accept-ranges` = "bytes", `transfer-encoding` = "chunked", 
        `content-type` = "text/html; charset=utf-8", `content-language` = "en"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 404L, version = "HTTP/1.1", 
        headers = structure(list(date = "Fri, 31 May 2024 08:10:15 GMT", 
            server = "Apache", vary = "accept-language,accept-charset", 
            `accept-ranges` = "bytes", `transfer-encoding` = "chunked", 
            `content-type` = "text/html; charset=utf-8", `content-language` = "en"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\"\n  \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\n<html xmlns=\"http://www.w3.org/1999/xhtml\" lang=\"en\" xml:lang=\"en\">\n<head>\n<title>Object not found!</title>\n<link rev=\"made\" href=\"mailto:cran-sysadmin@r-project.org\" />\n<style type=\"text/css\"><!--/*--><![CDATA[/*><!--*/ \n    body { color: #000000; background-color: #FFFFFF; }\n    a:link { color: #0000CC; }\n    p, address {margin-left: 3em;}\n    span {font-size: smaller;}\n/*]]>*/--></style>\n</head>\n\n<body>\n<h1>Object not found!</h1>\n<p>\n\n\n    The requested URL was not found on this server.\n\n  \n\n    If you entered the URL manually please check your\n    spelling and try again.\n\n  \n\n</p>\n<p>\nIf you think this is a server error, please contact\nthe <a href=\"mailto:cran-sysadmin@r-project.org\">webmaster</a>.\n\n</p>\n\n<h2>Error 404</h2>\n<address>\n  <a href=\"/\">cran.r-project.org</a><br />\n  <span>Apache</span>\n</address>\n</body>\n</html>\n\n"), 
    date = structure(1717143015, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.000103, 
    connect = 0, pretransfer = 0.000268, starttransfer = 0.040082, 
    total = 0.040163)), class = "response")
